import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import emailjs from '@emailjs/browser';

const EMAILJS_SERVICE_ID = 'service_gb7mdqe';
const EMAILJS_TEMPLATE_ID = 'template_chcvjfo';
const EMAILJS_PUBLIC_KEY = 'VH959_bwGbccRgYNp';

const captureContent = async (): Promise<HTMLCanvasElement> => {
  const el = document.getElementById('print-area');
  if (!el) throw new Error('Print area not found');

  // Hide no-print elements
  const noPrint = document.querySelectorAll('.no-print');
  const saved: string[] = [];
  noPrint.forEach(e => {
    saved.push((e as HTMLElement).style.display);
    (e as HTMLElement).style.display = 'none';
  });

  try {
    return await html2canvas(el, {
      scale: 2,
      useCORS: true,
      logging: false,
      backgroundColor: '#ffffff',
    });
  } finally {
    noPrint.forEach((e, i) => {
      (e as HTMLElement).style.display = saved[i];
    });
  }
};

export const exportToPDF = async (): Promise<void> => {
  const canvas = await captureContent();
  const imgData = canvas.toDataURL('image/png');
  
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pdfWidth = pdf.internal.pageSize.getWidth();
  const pdfHeight = pdf.internal.pageSize.getHeight();
  const imgWidth = pdfWidth - 20; // 10mm margin each side
  const imgHeight = (canvas.height * imgWidth) / canvas.width;
  
  // MESDA header
  pdf.setFillColor(165, 204, 49); // #A5CC31
  pdf.rect(0, 0, pdfWidth, 3, 'F');
  pdf.setFontSize(16);
  pdf.setTextColor(123, 165, 29); // #7BA51D
  pdf.text('MESDA', 10, 12);
  pdf.setFontSize(10);
  pdf.setTextColor(100, 100, 100);
  pdf.text('ROI Calculator Report', 35, 12);
  
  let heightLeft = imgHeight;
  let position = 18; // Start below header
  
  pdf.addImage(imgData, 'PNG', 10, position, imgWidth, imgHeight);
  heightLeft -= (pdfHeight - 22);
  
  while (heightLeft > 0) {
    position = heightLeft - imgHeight + 18;
    pdf.addPage();
    pdf.setFillColor(165, 204, 49);
    pdf.rect(0, 0, pdfWidth, 2, 'F');
    pdf.addImage(imgData, 'PNG', 10, position, imgWidth, imgHeight);
    heightLeft -= (pdfHeight - 22);
  }
  
  // Footer
  const pageCount = pdf.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    pdf.text(
      `Generated by MESDA ROI Calculator - ${new Date().toLocaleDateString()} - Page ${i}/${pageCount}`,
      pdfWidth / 2, pdfHeight - 5, { align: 'center' }
    );
  }
  
  pdf.save(`MESDA_ROI_Report_${new Date().toISOString().split('T')[0]}.pdf`);
};

export const sendPDFToEmail = async (userEmail: string): Promise<void> => {
  const canvas = await captureContent();
  const imageData = canvas.toDataURL('image/png');

  const templateParams = {
    to_email: userEmail,
    from_name: 'MESDA ROI Calculator',
    message: `Your MESDA ROI Calculator report generated on ${new Date().toLocaleDateString()}.`,
    attachment: imageData,
  };

  await emailjs.send(EMAILJS_SERVICE_ID, EMAILJS_TEMPLATE_ID, templateParams, EMAILJS_PUBLIC_KEY);
};
